[project]
name = "iis-2026"
version = "0.1.0"
description = "Projekt za predmet Inzenirstvo inteligentnega sistema"
readme = "README.md"
authors = [
    { name = "Jan Kvartic", email = "jan.kvartic@student.um.si" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "evidently>=0.7.1,<0.8.0",
    "great-expectations==0.18.21",
    "joblib>=1.5.3",
    "lxml>=6.0.3",
    "numpy<2",
    "pandas<3",
    "pyaml>=26.2.1",
    "requests>=2.33.1",
    "scikit-learn<2",
    "tensorflow>=2.19.0,<3.0.0",
]

[project.scripts]
iis-2026 = "iis_2026:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
